In [1]:
# Encoding : It converts non-numeric data into numeric form to make it usable for analysis and machine learning models.
# Mostly use when there is repeted data is used like colunm contains only YES/NO or MALE?FEMALE etc/

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("data.csv")
df.head()

,CustomerID,EducationLevel,Experience,SubscriptionType,PaymentScore,City,Churn,Gender
0,201,Graduate,3 years,Basic,4,Mumbai,Yes,Female
1,202,12th,2 yrs,Premium,5,Delhi,No,Male
2,203,Post Graduate,Five,Standard,3,Bangalore,Yes,Female
3,204,UG,1 year,Basic,Two,Delhi,No,Male
4,205,Graduate,NaN,Premium,5,Mumbai,Yes,Male

In [6]:
df.isnull().sum()

CustomerID          0
EducationLevel      1
Experience          1
SubscriptionType    0
PaymentScore        1
City                0
Churn               0
Gender              0
dtype: int64

In [9]:
en_df = df[["Churn","Gender"]]
pd.get_dummies(en_df)

    Churn_No  Churn_Yes  Gender_Female  Gender_Male
0      False       True           True        False
1       True      False          False         True
2      False       True           True        False
3       True      False          False         True
4      False       True          False         True
5       True      False          False         True
6      False       True           True        False
7       True      False          False         True
8      False       True           True        False
9       True      False          False         True
10     False       True          False         True
11      True      False           True        False

In [1]:
# will Learn one hot encoding later as used in data science and machine learning consepts we use strikit learn lib for that

In [ ]:
# what is Lable Encoding :