In [1]:
# handeling duplicate data 
# Duplicate Data : entier row is repeated in data called duplicated data

In [2]:
import pandas as pd

In [10]:
data = { "name": ['a','b','c','d','a','c'] , "English" : [8,7,5,8,8,5], "Math" : [2,3,4,5,2,6]}
df = pd.DataFrame(data)
df

  name  English  Math
0    a        8     2
1    b        7     3
2    c        5     4
3    d        8     5
4    a        8     2
5    c        5     6

In [11]:
# As we can see row 4th is repeated
# but to check for large data let's make new colunm duplicated
# duplicated() gives bool values as output

df.duplicated()
df["duplicated"] = df.duplicated()
df

  name  English  Math  duplicated
0    a        8     2       False
1    b        7     3       False
2    c        5     4       False
3    d        8     5       False
4    a        8     2        True
5    c        5     6       False

In [13]:
# To remove duplicates use drop_duplicates fun
# If duplicates of same row is mulltiple then use keep attribute keep = True
# And use inplace tto make change is orignal df
# first remove colunm duplicated caues it will be also compared while checking duplicated
 
df.drop("duplicated", axis=1, inplace=True)
df.drop_duplicates(inplace=True)
df

  name  English  Math
0    a        8     2
1    b        7     3
2    c        5     4
3    d        8     5
5    c        5     6

In [14]:
# AS we can see 4th row is removed 
# If you work on real data it works same as above